#!/usr/bin/env python3
"""Extract the deterministic Video Studio planner closure from Podcastor."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path


ROOT_SYMBOLS = {
    "normalize_script_director",
    "normalize_director_document",
    "normalize_producer_analysis",
    "normalize_requirement_document",
    "normalize_creative_plan",
    "normalize_scene_groups",
    "build_render_contract_package",
    "build_composition_preview_html",
    "build_final_video_html",
    "is_current_bespoke_html_design",
    "is_current_bespoke_html_asset",
    "_sanitize_custom_html_fragment",
    "_sanitize_custom_css",
    "scale_scene_outline_durations",
    "fallback_script",
    "fallback_script_director",
    "fallback_director_document",
    "fallback_storyboard",
    "generate_storyboard_from_creative_plan",
}


def declared_names(node: ast.AST) -> list[str]:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        return [node.name]
    if isinstance(node, (ast.Assign, ast.AnnAssign)):
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        return [target.id for target in targets if isinstance(target, ast.Name)]
    return []


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()

    source_text = args.source.read_text(encoding="utf-8")
    source_lines = source_text.splitlines(keepends=True)
    tree = ast.parse(source_text)

    nodes: dict[str, ast.AST] = {}
    imports: list[ast.AST] = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(node)
        for name in declared_names(node):
            nodes[name] = node

    missing = sorted(ROOT_SYMBOLS - nodes.keys())
    if missing:
        raise SystemExit(f"planner symbols missing from source: {', '.join(missing)}")

    selected: set[ast.AST] = set()
    pending = list(ROOT_SYMBOLS)
    visited: set[str] = set()
    while pending:
        name = pending.pop()
        if name in visited:
            continue
        visited.add(name)
        node = nodes.get(name)
        if node is None:
            continue
        selected.add(node)
        for child in ast.walk(node):
            if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load) and child.id in nodes:
                pending.append(child.id)

    used_names = {
        child.id
        for node in selected
        for child in ast.walk(node)
        if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load)
    }
    selected_imports = []
    for node in imports:
        aliases = node.names if isinstance(node, (ast.Import, ast.ImportFrom)) else []
        exposed = {alias.asname or alias.name.split(".")[0] for alias in aliases}
        if exposed & used_names:
            selected_imports.append(node)

    chunks = [
        '"""Extracted deterministic Video Studio planner code. Do not edit directly.\n\n'
        f"Source: {args.source}\n"
        'Generated by scripts/extract-planner.py.\n"""\n\n',
        "from __future__ import annotations\n\n",
    ]
    for node in sorted(selected_imports, key=lambda item: item.lineno):
        chunks.append("".join(source_lines[node.lineno - 1 : node.end_lineno]).rstrip() + "\n")
    chunks.append("\n")
    for node in sorted(selected, key=lambda item: item.lineno):
        chunks.append("".join(source_lines[node.lineno - 1 : node.end_lineno]).rstrip() + "\n\n\n")

    output = "".join(chunks).rstrip() + "\n"
    forbidden = ("call_video_studio_llm", "api.siliconflow", "api.deepseek", "VIDEO_STUDIO_HTML_LLM")
    leaked = [token for token in forbidden if token in output]
    if leaked:
        raise SystemExit(f"extracted planner retained forbidden LLM symbols: {', '.join(leaked)}")

    args.destination.parent.mkdir(parents=True, exist_ok=True)
    args.destination.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
